version: '3.8'
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - bridge
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8079:8079"
    networks:
      - bridge
    depends_on:
      - eureka-server
    env_file:
      - ./api-gateway/.env
  user-microservice:
    build:
        context: ./user-microservice
        dockerfile: Dockerfile
    container_name: user-microservice
    ports:
      - "8080:8080"
    networks:
      - bridge
    depends_on:
      - eureka-server
      - api-gateway
    env_file:
      - ./user-microservice/.env
  product-microservice:
    build:
      context: ./product-microservice
      dockerfile: Dockerfile
    container_name: product-microservice
    ports:
      - "8082:8082"
    networks:
      - bridge
    depends_on:
      - eureka-server
      - api-gateway
      - user-microservice
    env_file:
      - ./product-microservice/.env
  log-microservice:
    build:
      context: ./log-microservice
      dockerfile: Dockerfile
    container_name: log-microservice
    ports:
      - "8081:8081"
    networks:
      - bridge
    depends_on:
        - eureka-server
        - api-gateway
        - user-microservice
        - product-microservice
    env_file:
        - ./log-microservice/.env

networks:
    bridge:
        driver: bridge
        name: project-network
